language: python

# Version number
python:
  - 2.7

runtime:
  nodePool: dynamic__x86_64__CentOS_7__c4_large

build:
  pre_ci_boot:
    image_name: drydock/c7
    image_tag: master
    pull: true
    
  ci:
    - python -V
    - docker ps
  #  - docker build -t=test .
    - docker images
    
resources:

  - name: version-resource1cent
    type: version
    seed:
      versionName: "0.0.1-beta"

  - name: repo1cent
    type: gitRepo
    integration: github
    pointer:
      sourceName: Varsha-Arun/sample_pipelines
      branch: master
      
  - name: notify-slack1cent
    type: notification
    pointer:
      method: email
      recipients: 
       # - deepika@shippable.com
        - varsha@shippable.com
      
jobs:
  - name: simplerunsh1cent
    type: runSh
    runtime:
      nodePool: dynamic__x86_64__CentOS_7__c4_large
    steps:
      - IN: repo
      - TASK:
        - script: ls
       # - script: sleep 3m
        #- script: ./GET/infra-repo/infra-repo/provision.sh
    always:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack1cent
      
triggers:
   - name: triggersp1cent
     type: trigger
     version:
       counter: 8
       
   - name: triggersp2cent
     type: trigger
     version:
       counter: 7
       
   - name: triggersp3cent
     type: trigger
     version:
       counter: 1
    
